default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  username: root
  password: root
  database: pokedex-api_development

test:
  <<: *default
  host: localhost
  username: root
  password: root
  database: pokedex-api_test

production:
  <<: *default
  host: localhost
  username: root
  password: root
  database: pokedex-api_production
